require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BookingsExtrasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BookingsExtra. As you add validations to BookingsExtra, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookingsExtrasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all bookings_extras as @bookings_extras" do
      bookings_extra = BookingsExtra.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:bookings_extras)).to eq([bookings_extra])
    end
  end

  describe "GET #show" do
    it "assigns the requested bookings_extra as @bookings_extra" do
      bookings_extra = BookingsExtra.create! valid_attributes
      get :show, {:id => bookings_extra.to_param}, valid_session
      expect(assigns(:bookings_extra)).to eq(bookings_extra)
    end
  end

  describe "GET #new" do
    it "assigns a new bookings_extra as @bookings_extra" do
      get :new, {}, valid_session
      expect(assigns(:bookings_extra)).to be_a_new(BookingsExtra)
    end
  end

  describe "GET #edit" do
    it "assigns the requested bookings_extra as @bookings_extra" do
      bookings_extra = BookingsExtra.create! valid_attributes
      get :edit, {:id => bookings_extra.to_param}, valid_session
      expect(assigns(:bookings_extra)).to eq(bookings_extra)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BookingsExtra" do
        expect {
          post :create, {:bookings_extra => valid_attributes}, valid_session
        }.to change(BookingsExtra, :count).by(1)
      end

      it "assigns a newly created bookings_extra as @bookings_extra" do
        post :create, {:bookings_extra => valid_attributes}, valid_session
        expect(assigns(:bookings_extra)).to be_a(BookingsExtra)
        expect(assigns(:bookings_extra)).to be_persisted
      end

      it "redirects to the created bookings_extra" do
        post :create, {:bookings_extra => valid_attributes}, valid_session
        expect(response).to redirect_to(BookingsExtra.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved bookings_extra as @bookings_extra" do
        post :create, {:bookings_extra => invalid_attributes}, valid_session
        expect(assigns(:bookings_extra)).to be_a_new(BookingsExtra)
      end

      it "re-renders the 'new' template" do
        post :create, {:bookings_extra => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bookings_extra" do
        bookings_extra = BookingsExtra.create! valid_attributes
        put :update, {:id => bookings_extra.to_param, :bookings_extra => new_attributes}, valid_session
        bookings_extra.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested bookings_extra as @bookings_extra" do
        bookings_extra = BookingsExtra.create! valid_attributes
        put :update, {:id => bookings_extra.to_param, :bookings_extra => valid_attributes}, valid_session
        expect(assigns(:bookings_extra)).to eq(bookings_extra)
      end

      it "redirects to the bookings_extra" do
        bookings_extra = BookingsExtra.create! valid_attributes
        put :update, {:id => bookings_extra.to_param, :bookings_extra => valid_attributes}, valid_session
        expect(response).to redirect_to(bookings_extra)
      end
    end

    context "with invalid params" do
      it "assigns the bookings_extra as @bookings_extra" do
        bookings_extra = BookingsExtra.create! valid_attributes
        put :update, {:id => bookings_extra.to_param, :bookings_extra => invalid_attributes}, valid_session
        expect(assigns(:bookings_extra)).to eq(bookings_extra)
      end

      it "re-renders the 'edit' template" do
        bookings_extra = BookingsExtra.create! valid_attributes
        put :update, {:id => bookings_extra.to_param, :bookings_extra => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested bookings_extra" do
      bookings_extra = BookingsExtra.create! valid_attributes
      expect {
        delete :destroy, {:id => bookings_extra.to_param}, valid_session
      }.to change(BookingsExtra, :count).by(-1)
    end

    it "redirects to the bookings_extras list" do
      bookings_extra = BookingsExtra.create! valid_attributes
      delete :destroy, {:id => bookings_extra.to_param}, valid_session
      expect(response).to redirect_to(bookings_extras_url)
    end
  end

end
